spring.application.name=taskmaster
server.port=8080

spring.datasource.url=jdbc:mysql://database-1.cvs4iaegiul2.eu-north-1.rds.amazonaws.com:3306/taskmaster_db?createDatabaseIfNotExist=true&useSSL=true&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=admin
spring.datasource.password=kubernetes75488

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect